import { apiFetch, apiUrl } from "@/lib/api";

export type LearnerPurpose = "chat" | "courseware" | "flashcards" | "quiz";

export interface SubjectRef { subject_id: string; label: string; path: string[]; confidence: number; source: string; confirmed: boolean }
export interface PreferenceEvidence { id: string; value: string; category: string; state: "explicit" | "inferred" | "rejected"; confidence: number; evidence_refs: string[] }
export interface LearnerProfile { scope: "global" | "subject"; subject?: SubjectRef | null; inference_enabled: boolean; preferences: PreferenceEvidence[]; concept_signals: Array<{ concept_id: string; label: string; support_level: string; confidence: number; attempt_count: number; misconception_tags: string[]; evidence_refs: string[]; mastery_probability?: number; observation_count?: number; verified_observation_count?: number; module_id?: string | null }>; strategy_evidence: Array<{ id: string; task_type: string; positive_weight: number; negative_weight: number; confidence: number; evidence_refs: string[]; event_ids?: string[]; strategy: Record<string, unknown> }>; understanding?: { status: "starting" | "learning" | "familiar" | "verified"; concept_count: number; observed_concept_count: number; coverage: number; verified_mastery: number; confidence: number; recent_activity_at?: string | null; review_load: number } | null; updated_at: string; needs_rebuild: boolean }
export interface LearnerOverview { global: LearnerProfile; subjects: LearnerProfile[]; inference_enabled: boolean; pending_subjects: LearnerProfile[]; memory_reconcile?: { state: string; last_completed_at?: string | null; imported?: number } }
export type ReflectionStatus = "candidate" | "confirmed" | "rejected" | "stale" | "needs_rebuild";
export interface LearnerReflection { reflection_id: string; scope: "global" | "subject"; subject?: SubjectRef | null; category: "goal" | "explanation" | "pacing" | "feedback" | "constraint" | "concept" | "strategy"; value: string; status: ReflectionStatus; source_state?: "explicit" | "inferred" | "rejected" | null; confidence: number; evidence_refs: string[]; updated_at: string; expires_at?: string | null; applies_to_compass: boolean; reason: string }
export interface LearningKnowledgeGraph { subject: SubjectRef; nodes: Array<{ concept_id: string; label: string; module_id: string; module_label: string; evidence_chunk_ids: string[]; confidence: number }>; edges: Array<{ source_concept_id: string; target_concept_id: string; relation: "prerequisite" | "part_of" | "related_to"; evidence_chunk_ids: string[]; confidence: number }>; source_refs: string[] }
export interface PersonalizationContext { purpose: LearnerPurpose; subject?: SubjectRef | null; active_goal?: string | null; plan: Record<string, unknown> & { rationale?: Array<{ source: string; text: string; evidence_refs: string[] }> }; relevant_concept_signals: LearnerProfile["concept_signals"]; constraints: string[]; evidence_refs: string[]; degraded: boolean; degradation_reason?: string | null }
export interface LearnerEvidence { signal_id: string; kind: string; payload: Record<string, unknown>; evidence_refs: string[]; occurred_at: string }
export type UserLearnerEvent = { event_type: "self_assessment" | "chat_correction"; subject_id?: string; concept_id?: string; concept_label?: string; observation?: "known" | "unknown" | "uncertain"; payload?: Record<string, unknown> };

async function json<T>(response: Response): Promise<T> {
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || `Request failed: ${response.status}`);
  return response.json() as Promise<T>;
}
export const getLearnerOverview = () => apiFetch(apiUrl("/api/v1/memory/learner/overview"), { cache: "no-store" }).then(json<LearnerOverview>);
export const getLearnerSubject = (id: string) => apiFetch(apiUrl(`/api/v1/memory/learner/subjects/${encodeURIComponent(id)}`), { cache: "no-store" }).then(json<LearnerProfile>);
export const getLearningKnowledgeGraph = (id: string) => apiFetch(apiUrl(`/api/v1/memory/learner/subjects/${encodeURIComponent(id)}/knowledge-graph`), { cache: "no-store" }).then(json<LearningKnowledgeGraph>);
export const setLearnerInference = (enabled: boolean) => apiFetch(apiUrl(`/api/v1/memory/learner/inference?enabled=${enabled}`), { method: "PATCH" }).then(json<LearnerProfile>);
export const saveLearnerPreference = (input: { value: string; category: string; subject?: SubjectRef | null }) => apiFetch(apiUrl(`/api/v1/memory/learner/preferences/${input.subject ? "subject" : "global"}`), { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }).then(json<{ profiles: LearnerProfile[] }>);
export const previewPersonalization = (input: { purpose: LearnerPurpose; title?: string; text?: string; current_instruction?: string }) => apiFetch(apiUrl("/api/v1/memory/learner/context/preview"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }).then(json<PersonalizationContext>);
export const getLearnerEvidence = (subjectId?: string) => apiFetch(apiUrl(`/api/v1/memory/learner/evidence${subjectId ? `?subject_id=${encodeURIComponent(subjectId)}` : ""}`), { cache: "no-store" }).then(json<{ evidence: LearnerEvidence[] }>);
export const deleteLearnerEvidence = (signalId: string) => apiFetch(apiUrl(`/api/v1/memory/learner/evidence/${encodeURIComponent(signalId)}`), { method: "DELETE" }).then(json<{ deleted: boolean }>);
export const getLearnerReflections = (subjectId?: string) => apiFetch(apiUrl(`/api/v1/memory/learner/reflections${subjectId ? `?subject_id=${encodeURIComponent(subjectId)}` : ""}`), { cache: "no-store" }).then(json<{ reflections: LearnerReflection[]; summary: Record<ReflectionStatus | "applies_to_compass", number> }>);
export const updateLearnerReflectionStatus = (reflectionId: string, status: "candidate" | "confirmed" | "rejected") => apiFetch(apiUrl(`/api/v1/memory/learner/reflections/${encodeURIComponent(reflectionId)}`), { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }).then(json<{ reflection: LearnerReflection }>);
export const confirmLearnerSubject = (subject: SubjectRef) => apiFetch(apiUrl(`/api/v1/memory/learner/subjects/${encodeURIComponent(subject.subject_id)}/confirm`), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label: subject.label, path: subject.path }) }).then(json<{ profile: LearnerProfile }>);
export const correctLearnerSubject = (oldSubjectId: string, input: { subject_id: string; label: string; path: string[] }) => apiFetch(apiUrl(`/api/v1/memory/learner/subjects/${encodeURIComponent(oldSubjectId)}/correct`), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }).then(json<{ profile: LearnerProfile }>);
export const recordLearnerEvent = (input: UserLearnerEvent) => apiFetch(apiUrl("/api/v1/memory/learner/events"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }).then(json<{ event_id: string; profiles: LearnerProfile[] }>);
export const reconcileLearnerMemory = () => apiFetch(apiUrl("/api/v1/memory/learner/reconcile-memory"), { method: "POST" }).then(json<{ state: string }>);
