"use client";
/* eslint-disable i18n/no-literal-ui-text -- this Profile application is intentionally Chinese-first in this release. */

import { use, useCallback, useEffect, useState } from "react";
import { Check, Trash2 } from "lucide-react";
import { PageBackLink } from "@/components/navigation/PageBackLink";
import { confirmLearnerSubject, correctLearnerSubject, deleteLearnerEvidence, getLearnerEvidence, getLearnerSubject, getLearningKnowledgeGraph, recordLearnerEvent, type LearnerEvidence, type LearnerProfile, type LearningKnowledgeGraph } from "@/lib/learner-model-api";

export default function LearnerSubjectPage({ params }: { params: Promise<{ subjectId: string }> }) {
  const { subjectId } = use(params);
  const [profile, setProfile] = useState<LearnerProfile | null>(null);
  const [evidence, setEvidence] = useState<LearnerEvidence[]>([]);
  const [graph, setGraph] = useState<LearningKnowledgeGraph | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    const [nextProfile, nextEvidence, nextGraph] = await Promise.all([getLearnerSubject(subjectId), getLearnerEvidence(subjectId), getLearningKnowledgeGraph(subjectId)]);
    setProfile(nextProfile); setEvidence(nextEvidence.evidence); setGraph(nextGraph);
  }, [subjectId]);
  useEffect(() => { void load().then(() => setError("")).catch((cause) => setError(cause instanceof Error ? cause.message : "无法加载学习模型")); }, [load]);
  async function action(work: () => Promise<void>) { setBusy(true); setError(""); try { await work(); } catch (cause) { setError(cause instanceof Error ? cause.message : "操作未完成，请重试"); } finally { setBusy(false); } }
  async function remove(signalId: string) { await action(async () => { await deleteLearnerEvidence(signalId); await load(); }); }
  async function confirm() { await action(async () => { await confirmLearnerSubject(subject); await load(); }); }
  async function correct() { const label = window.prompt("请输入正确的学科名称", subject.label)?.trim(); if (!label) return; const subjectId = window.prompt("请输入稳定学科标识（例如 mathematics-algebra）", subject.subject_id)?.trim(); if (!subjectId) return; await action(async () => { await correctLearnerSubject(subject.subject_id, { subject_id: subjectId, label, path: [label] }); window.location.assign(`/profile/learning-model/${encodeURIComponent(subjectId)}`); }); }
  async function selfAssess(observation: "known" | "unknown") { await action(async () => { await recordLearnerEvent({ event_type: "self_assessment", subject_id: subject.subject_id, concept_id: "subject-self-assessment", concept_label: "学科整体自评（待验证）", observation, payload: {} }); await load(); }); }
  if (!profile?.subject) return <div className="space-y-3 p-10 text-sm text-[var(--muted-foreground)]"><p>{error || "正在加载学习模型…"}</p><PageBackLink href="/profile/learning-model">返回我的学习模型</PageBackLink></div>;
  const subject = profile.subject;
  return <div className="mx-auto max-w-5xl space-y-6 px-4 py-6 sm:px-6 sm:py-10">
    <PageBackLink href="/profile/learning-model">返回我的学习模型</PageBackLink>
    {error && <p className="rounded-md border border-red-300 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-serif text-3xl font-semibold">{subject.label}</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">{subject.path.join(" · ")}</p></div><div className="flex gap-2">{subject.confirmed ? <span className="inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs text-emerald-700"><Check className="h-3.5 w-3.5"/>已确认分类</span> : <button type="button" disabled={busy} onClick={() => void confirm()} className="inline-flex items-center gap-1 rounded-full border border-amber-300 px-3 py-1 text-xs text-amber-700 disabled:opacity-50"><Check className="h-3.5 w-3.5"/>确认此分类</button>}<button type="button" disabled={busy} onClick={() => void correct()} className="rounded-full border px-3 py-1 text-xs disabled:opacity-50">纠正学科</button></div></header>
    <section className="rounded-xl border p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">概念状态</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">{profile.understanding ? `当前：${({ starting: "刚开始", learning: "学习中", familiar: "较熟悉", verified: "已验证掌握" } as Record<string, string>)[profile.understanding.status]}；已验证理解 ${Math.round(profile.understanding.verified_mastery * 100)}%，待复习 ${profile.understanding.review_load} 项。` : "尚无可验证的概念练习证据。"}</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void selfAssess("unknown")} className="rounded-md border px-2.5 py-1.5 text-xs">我还不熟悉</button><button type="button" disabled={busy} onClick={() => void selfAssess("known")} className="rounded-md border px-2.5 py-1.5 text-xs">我已学过</button></div></div><div className="mt-3 space-y-2">{profile.concept_signals.map((item) => <div key={item.concept_id} className="flex flex-col gap-1 rounded-md bg-[var(--muted)]/40 p-3 text-sm sm:flex-row sm:justify-between sm:gap-3"><span className="min-w-0 break-words">{item.label}</span><span className="text-xs text-[var(--muted-foreground)] sm:text-right">{item.support_level} · {item.verified_observation_count ?? 0} 次可判分证据 · {Math.round((item.mastery_probability ?? 0) * 100)}%</span></div>)}</div></section>
    <section className="rounded-xl border p-4 sm:p-5"><h2 className="font-semibold">学习知识地图</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">图谱定义概念之间的材料依据关系；BKT 覆盖在对应节点上，用于寻找前置薄弱点和下一步复习重点。</p>{graph?.nodes.length ? <div className="mt-4 space-y-3">{graph.nodes.map((node) => { const signal = profile.concept_signals.find((item) => item.concept_id === node.concept_id); const prerequisites = graph.edges.filter((edge) => edge.relation === "prerequisite" && edge.target_concept_id === node.concept_id).map((edge) => graph.nodes.find((candidate) => candidate.concept_id === edge.source_concept_id)?.label).filter(Boolean); return <div key={node.concept_id} className="rounded-lg border border-[var(--border)] bg-[var(--muted)]/30 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{node.label}</p><span className="text-xs text-[var(--muted-foreground)]">{signal ? `${Math.round((signal.mastery_probability ?? 0) * 100)}% · ${signal.verified_observation_count ?? 0} 次验证` : "尚未练习"}</span></div><p className="mt-1 text-xs text-[var(--muted-foreground)]">{node.module_label}{prerequisites.length ? ` · 前置：${prerequisites.join("、")}` : ""}</p></div>; })}</div> : <div className="mt-4 rounded-lg border border-dashed border-[var(--border)] p-4 text-sm text-[var(--muted-foreground)]">完成一次材料分析与生成后，TraitTutor 会从材料中建立有出处的概念关系；没有证据时不会猜测前置关系。</div>}</section>
    <section className="rounded-xl border p-5"><h2 className="font-semibold">策略证据</h2><div className="mt-3 space-y-2">{profile.strategy_evidence.length ? profile.strategy_evidence.map((item) => <div key={item.id} className="rounded-md bg-[var(--muted)]/40 p-3 text-sm">{item.task_type} · 正向 {item.positive_weight} / 负向 {item.negative_weight} · 已验证事件 {item.event_ids?.length ?? 0}</div>) : <p className="text-sm text-[var(--muted-foreground)]">尚无策略反馈。</p>}</div></section>
    <section className="rounded-xl border p-5"><h2 className="font-semibold">逐条证据治理</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">删除后，相关概念和策略会从剩余证据重新计算。</p><div className="mt-4 space-y-2">{evidence.length ? evidence.map((item) => <div key={item.signal_id} className="flex items-center justify-between gap-3 rounded-md border p-3"><div className="min-w-0"><p className="text-sm font-medium">{item.kind}</p><p className="truncate text-xs text-[var(--muted-foreground)]">{String(item.payload.value || item.payload.concept || item.payload.strategy || "学习信号")}</p></div><button type="button" disabled={busy} onClick={() => void remove(item.signal_id)} className="inline-flex shrink-0 items-center gap-1 rounded-md border border-red-200 px-2 py-1.5 text-xs text-red-700 disabled:opacity-50"><Trash2 className="h-3.5 w-3.5"/>删除</button></div>) : <p className="text-sm text-[var(--muted-foreground)]">该学科还没有可治理的事件。</p>}</div></section>
  </div>;
}
