"""Typed, privacy-bounded product telemetry contracts."""

from __future__ import annotations

from .alerts import (
    TELEMETRY_ALERT_EMAIL_FROM_ENV,
    TELEMETRY_ALERT_EMAIL_PASSWORD_ENV,
    TELEMETRY_ALERT_EMAIL_SMTP_HOST_ENV,
    TELEMETRY_ALERT_EMAIL_SMTP_PORT_ENV,
    TELEMETRY_ALERT_EMAIL_TO_ENV,
    TELEMETRY_ALERT_EMAIL_USERNAME_ENV,
    TELEMETRY_ALERT_PAGERDUTY_EVENTS_URL_ENV,
    TELEMETRY_ALERT_PAGERDUTY_ROUTING_KEY_ENV,
    TELEMETRY_ALERT_WEBHOOK_TIMEOUT_MS_ENV,
    TELEMETRY_ALERT_WEBHOOK_URL_ENV,
    PagerDutyTelemetryAlertHook,
    SmtpTelemetryAlertHook,
    WebhookTelemetryAlertHook,
    create_configured_telemetry_alert_hook,
)
from .delivery import (
    AsyncBoundedProductEventSink,
    JsonlTelemetryBatchWriter,
    NoOpTelemetryAlertHook,
    TelemetryAggregate,
    TelemetryBatch,
    TelemetryDeliveryAlert,
    TelemetryDeliveryConfig,
    TelemetryDeliveryStats,
    create_product_event_sink,
    get_configured_product_event_sink,
)
from .pricing import (
    TELEMETRY_PRICING_PATH_ENV,
    FileTokenPricing,
    ModelTokenPrice,
    NoOpTokenPricing,
    TokenPricing,
    create_configured_token_pricing,
)
from .product_events import (
    EVENT_REGISTRY,
    InMemoryProductEventSink,
    NoOpProductEventSink,
    ProductEventEnvelope,
    ProductEventSink,
    record_product_event,
)

__all__ = [
    "EVENT_REGISTRY",
    "AsyncBoundedProductEventSink",
    "InMemoryProductEventSink",
    "JsonlTelemetryBatchWriter",
    "NoOpProductEventSink",
    "NoOpTelemetryAlertHook",
    "NoOpTokenPricing",
    "ProductEventEnvelope",
    "ProductEventSink",
    "TelemetryAggregate",
    "TELEMETRY_ALERT_EMAIL_FROM_ENV",
    "TELEMETRY_ALERT_EMAIL_PASSWORD_ENV",
    "TELEMETRY_ALERT_EMAIL_SMTP_HOST_ENV",
    "TELEMETRY_ALERT_EMAIL_SMTP_PORT_ENV",
    "TELEMETRY_ALERT_EMAIL_TO_ENV",
    "TELEMETRY_ALERT_EMAIL_USERNAME_ENV",
    "TELEMETRY_ALERT_PAGERDUTY_EVENTS_URL_ENV",
    "TELEMETRY_ALERT_PAGERDUTY_ROUTING_KEY_ENV",
    "TELEMETRY_ALERT_WEBHOOK_TIMEOUT_MS_ENV",
    "TELEMETRY_ALERT_WEBHOOK_URL_ENV",
    "TelemetryBatch",
    "TelemetryDeliveryAlert",
    "TelemetryDeliveryConfig",
    "TelemetryDeliveryStats",
    "TELEMETRY_PRICING_PATH_ENV",
    "TokenPricing",
    "FileTokenPricing",
    "ModelTokenPrice",
    "create_product_event_sink",
    "create_configured_token_pricing",
    "create_configured_telemetry_alert_hook",
    "get_configured_product_event_sink",
    "record_product_event",
    "PagerDutyTelemetryAlertHook",
    "SmtpTelemetryAlertHook",
    "WebhookTelemetryAlertHook",
]
