"""
CLI Models Command
==================

Sync CC Switch providers into the code-defined LLM model file
(``config/models.local.yaml``) and list the currently configured models.
"""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

console = Console()


def _mask(key: str) -> str:
    """Mask an API key for display (e.g. ``sk-…1234``). Never prints a full key."""
    if len(key) >= 8:
        return key[:3] + "…" + key[-4:]
    if key:
        return "…"
    return "(none)"


def _record_to_entry(record) -> dict:
    """Convert a :class:`ModelRecord` to a YAML entry dict.

    ``api_key`` is written as a literal (CC Switch stores literal keys); only
    optional non-empty fields are emitted.
    """
    entry: dict = {
        "id": record.id,
        "name": record.name,
        "binding": record.binding,
        "base_url": record.base_url,
        "api_key": record.api_key,  # literal — see security note in header
        "model": record.model,
    }
    if record.extra_headers:
        entry["extra_headers"] = dict(record.extra_headers)
    if record.api_version:
        entry["api_version"] = record.api_version
    return entry


def build_models_yaml(
    records: list,
    existing: dict | None = None,
) -> tuple[dict, str]:
    """Merge CC Switch records into a models YAML dict.

    Merge by record ``id``: records override same-id entries in ``existing``;
    entries in ``existing`` whose id is NOT among the records are preserved
    (manual additions kept). Returns ``(data, active_id)`` where ``active_id``
    is the first ``is_current`` record's id, else the existing ``active`` if
    still present in the merged set, else the first merged id.
    """
    if not isinstance(existing, dict):
        existing = {}
    existing_models_raw = existing.get("models")
    if not isinstance(existing_models_raw, list):
        existing_models_raw = []

    record_entries: list[dict] = []
    record_ids: set[str] = set()
    active_from_current = ""
    for record, is_current in records:
        entry = _record_to_entry(record)
        record_entries.append(entry)
        record_ids.add(record.id)
        if is_current and not active_from_current:
            active_from_current = record.id

    # Preserve manual entries whose id is not claimed by a synced record.
    preserved: list[dict] = []
    for m in existing_models_raw:
        if isinstance(m, dict):
            mid = str(m.get("id") or "").strip()
            if mid and mid not in record_ids:
                preserved.append(m)

    merged_models: list[dict] = record_entries + preserved

    if active_from_current:
        active_id = active_from_current
    else:
        existing_active = str(existing.get("active") or "").strip()
        merged_ids = [
            str(m.get("id"))
            for m in merged_models
            if isinstance(m, dict) and m.get("id")
        ]
        if existing_active and existing_active in merged_ids:
            active_id = existing_active
        elif merged_models:
            active_id = str(merged_models[0].get("id"))
        else:
            active_id = ""

    data = {"active": active_id, "models": merged_models}
    return data, active_id


_HEADER = """\
# Code-defined LLM models for TraitTutor (auto-generated by `traittutor models sync-cc-switch`).
#
# This file is gitignored and holds REAL API KEYS as literals — NEVER commit it.
# Regenerate at any time with:  traittutor models sync-cc-switch
# Source: ~/.cc-switch/cc-switch.db (CC Switch providers).
#
# Schema: see config/models.local.example.yaml
"""


def register(app: typer.Typer) -> None:
    """Register the ``models`` command group on *app*."""

    @app.command("sync-cc-switch")
    def sync_cc_switch(
        db: Path = typer.Option(
            Path.home() / ".cc-switch" / "cc-switch.db",
            "--db",
            help="Path to the CC Switch SQLite DB (default ~/.cc-switch/cc-switch.db).",
        ),
        dry_run: bool = typer.Option(
            False,
            "--dry-run",
            help="Show what would be written without touching the file.",
        ),
        out: Path | None = typer.Option(
            None,
            "--out",
            help="Output YAML path (default: repo config/models.local.yaml).",
        ),
    ) -> None:
        """Import CC Switch providers into config/models.local.yaml.

        Reads mappable providers (claude -> custom_anthropic, codex -> custom)
        from the CC Switch SQLite DB and writes a code-defined models YAML.
        API keys are written as literals; existing manual entries are preserved.
        """
        import yaml

        from traittutor.services.models.cc_switch import iter_model_records
        from traittutor.services.models.local_catalog import local_models_path

        if not db.exists():
            console.print(f"[bold red]Error:[/] CC Switch DB not found: {db}")
            raise typer.Exit(code=1)

        records = iter_model_records(db)
        if not records:
            console.print("no mappable providers found")
            raise typer.Exit(code=0)

        target = out if out is not None else local_models_path()

        existing: dict | None = None
        if target.exists():
            try:
                loaded = yaml.safe_load(target.read_text(encoding="utf-8"))
                existing = loaded if isinstance(loaded, dict) else None
            except Exception:
                existing = None

        data, active_id = build_models_yaml(records, existing)

        table = Table(title="CC Switch -> models.local.yaml")
        table.add_column("*", justify="center")
        table.add_column("id")
        table.add_column("name")
        table.add_column("binding")
        table.add_column("model")
        table.add_column("base_url")
        table.add_column("api_key")
        for record, is_current in records:
            table.add_row(
                "*" if is_current else "",
                record.id,
                record.name,
                record.binding,
                record.model or "(none)",
                record.base_url,
                _mask(record.api_key),
            )
        console.print(table)

        if dry_run:
            console.print(f"\n\\[dry-run] target: {target}")
            console.print(
                f"\\[dry-run] active={active_id}  ({len(data['models'])} models)"
            )
            raise typer.Exit(code=0)

        target.parent.mkdir(parents=True, exist_ok=True)
        body = yaml.safe_dump(
            data,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
        )
        target.write_text(_HEADER + "\n" + body, encoding="utf-8")
        console.print(
            f"\n[green]Wrote[/] {len(data['models'])} models to {target}\n"
            f"active: {active_id}"
        )

    @app.command("list")
    def models_list() -> None:
        """List code-defined LLM models (keys are never shown)."""
        from traittutor.services.models import load_local_llm

        data = load_local_llm()
        if not data:
            console.print(
                "no models.local.yaml — run `traittutor models sync-cc-switch`"
            )
            raise typer.Exit(code=0)

        active_profile = data.get("active_profile_id")
        table = Table(title="Code-defined LLM models")
        table.add_column("*", justify="center")
        table.add_column("id")
        table.add_column("name")
        table.add_column("binding")
        table.add_column("model")
        table.add_column("base_url")
        for profile in data.get("profiles", []):
            models = profile.get("models") or []
            model_id = models[0]["model"] if models else "(none)"
            table.add_row(
                "*" if profile.get("id") == active_profile else "",
                str(profile.get("id")),
                str(profile.get("name")),
                str(profile.get("binding")),
                model_id,
                str(profile.get("base_url")),
            )
        console.print(table)
