#!/usr/bin/env python
"""Run the canonical Compose stack with ports from SQLite settings."""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SETTINGS_DIR = PROJECT_ROOT / "data" / "user" / "settings"
DOCKER_ENV_PATH = SETTINGS_DIR / "docker.env"
COMPOSE_PATH = PROJECT_ROOT / "compose.yaml"

DEFAULT_BACKEND_PORT = 8001
DEFAULT_FRONTEND_PORT = 3782


def _coerce_port(value: Any, default: int) -> int:
    try:
        port = int(str(value).strip())
    except (TypeError, ValueError):
        return default
    return port if 1 <= port <= 65535 else default


def render_docker_env(
    settings_dir: Path = SETTINGS_DIR,
    output_path: Path = DOCKER_ENV_PATH,
) -> dict[str, str]:
    """Render compose interpolation vars from canonical SQLite settings."""
    from traittutor.services.config.runtime_settings import RuntimeSettingsService

    system = RuntimeSettingsService(settings_dir, process_env={}).load_system(
        include_process_overrides=False
    )
    values = {
        "TRAITTUTOR_DOCKER_BACKEND_PORT": str(
            _coerce_port(system.get("backend_port"), DEFAULT_BACKEND_PORT)
        ),
        "TRAITTUTOR_DOCKER_FRONTEND_PORT": str(
            _coerce_port(system.get("frontend_port"), DEFAULT_FRONTEND_PORT)
        ),
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/docker_compose.py from TraitTutor SQLite settings.",
        "# Do not edit manually; update settings in TraitTutor instead.",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return values


def _compose_command(args: list[str]) -> list[str]:
    docker = shutil.which("docker")
    if not docker:
        raise SystemExit("docker was not found on PATH")
    return [
        docker,
        "compose",
        "--file",
        str(COMPOSE_PATH),
        "--env-file",
        str(DOCKER_ENV_PATH),
        *args,
    ]


def main(argv: list[str] | None = None) -> int:
    args = list(argv if argv is not None else sys.argv[1:])
    if not args:
        args = ["up", "-d"]

    values = render_docker_env()
    print(
        "Docker settings: "
        f"backend={values['TRAITTUTOR_DOCKER_BACKEND_PORT']} "
        f"frontend={values['TRAITTUTOR_DOCKER_FRONTEND_PORT']}",
        file=sys.stderr,
    )

    env = os.environ.copy()
    # Keep Docker execution detached from host process overrides.
    for key in (
        "BACKEND_PORT",
        "FRONTEND_PORT",
        "AUTH_ENABLED",
        "NEXT_PUBLIC_API_BASE",
        "NEXT_PUBLIC_API_BASE_EXTERNAL",
    ):
        env.pop(key, None)

    result = subprocess.run(_compose_command(args), cwd=str(PROJECT_ROOT), env=env, check=False)
    return int(result.returncode)


if __name__ == "__main__":
    raise SystemExit(main())
